name: Marketing Dental
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#989d86'
    - '#eaf1f7'
    - '#17120f'
    - '#507bbf'
    - '#4e4438'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
