name: Marketing Dental
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#619dd1'
    - '#4d505f'
    - '#c49480'
    - '#262930'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
