name: Marketing Dental
favicon: null
layout_spectrum: 0.99549
typography_spectrum: 0.49188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e4e0'
    - '#433c36'
    - '#a2694c'
    - '#7689c4'
    - '#c6916f'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0
purpose: []
