name: Marketing Dental
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25903
title: 'Marketing Dental '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2d3d7'
    - '#e7e7e9'
    - '#f0f1f3'
    - '#d8d9dd'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
