name: Marketing Dental
favicon: null
layout_spectrum: 0.01626
typography_spectrum: 0.47244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7c8c0'
    - '#342e18'
    - '#5e5e5e'
    - '#ffffff'
    - '#d38578'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
