name: Marketing Dental
favicon: null
layout_spectrum: 0.73917
typography_spectrum: 0.49188
title: 'Marketing Dental '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#619dd1'
    - '#4d505f'
    - '#c49480'
    - '#262930'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
